---
# Configure mariadb

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ mariadb_services_enable }}"
  when: mariadb_enable_service
